name: CLI Build
on:
  push:
    paths-ignore:
      - 'server'
      - 'server/**'
      - 'README.md'
      - 'LICENSE'
      - 'docker-compose.yml'
      - '.github/workflows/server.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Windows Compiler Tools
        run: sudo apt-get install mingw-w64
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
      - name: Cache Rust Project
        uses: Swatinem/rust-cache@v1
        with:
          working-directory: ./cli
      - name: Build Project
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-pc-windows-gnu --manifest-path ./cli/Cargo.toml
      - name: Upload Binary
        if: startsWith(github.ref, 'refs/tags/') == false
        uses: actions/upload-artifact@v3
        with:
          name: redts.exe
          path: target/x86_64-pc-windows-gnu/release/redts_cli.exe
